### ISSUE TITLE
add garry's mod support

### ISSUE THREAD

**Issue by udalipzh** [TRIGONIM/lua-express#2]
add garry's mod support

**Comment by AntyBD** [comment]
MADE IT AMD

**Comment by AMD-NICK** [comment]
Постарайтесь описать конкретный юз кейс, зачем это нужно в Garry's Mod, тогда я возможно напишу пост о том, как это запустить в гмоде. 

И, скорее всего, ваш юз кейс полностью можно покрыть вот этим: https://github.com/TRIGONIM/lua-long-polling/

https://blog.amd-nick.me/2023/12/15/long-polling

**Comment by AMD-NICK** [comment]
Мне так и не описали, зачем это может быть нужно в Garry's Mod. Когда я увижу весомые аргументы, то сможем восстановить обсуждение интеграции с Garry's Mod. Это возможно. После небольшого рефакторинга с заменой pegasus.
